[project]
name = "BiliTools-Remake"
version = "1.1.0a0"
description = "A simple media downloader for Bilibili"
authors = [
    { name = "NingmengLemon", email = "60469383+NingmengLemon@users.noreply.github.com" },
]
dependencies = ["tqdm>=4.66.5", "requests>=2.32.3", "qrcode>=8.0"]
requires-python = "<3.13,>=3.11"
readme = "README.md"
license = { text = "MIT" }

[project.scripts]
bilitools-cli = "bilitools.bilicli:boot"

[tool.uv]
package = true

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "types-qrcode>=8.0.0.20241004",
    "types-requests>=2.32.0.20241016",
    "types-tqdm>=4.66.0.20240417",
    "pytest>=8.3.3",
    "pytest-cov>=7.1.0",
    "pytest-asyncio>=1.4.0",
]
