from typing import Any, Literal
from http.cookiejar import MozillaCookieJar

from biliapis.template import APITemplate

class LoginAPIs(APITemplate):
    def exit_login(self) -> dict[Literal["redirectUrl"], str]: ...
    def __exit_login_req(self) -> str: ...
    def get_login_info(self) -> dict[str, Any]: ...
    def check_if_cookies_refresh_required(
        self,
    ) -> dict[Literal["refresh", "timestamp"], bool | int]: ...
    @staticmethod
    def get_correspond_path(ts: int) -> str: ...
    def get_refresh_csrf(self, correspond_path: str) -> str: ...
    def __get_refresh_csrf_req(self, corresp: str) -> str: ...
    def refresh_cookies(
        self, refresh_token: str, refresh_csrf: str
    ) -> dict[Literal["status", "message", "refresh_token"], Literal[0] | str]: ...
    def confirm_refresh_cookies(self, old_refresh_token: str) -> None: ...

class QRLoginAPIs(APITemplate):
    def get_login_qrcode_url(self) -> dict[Literal["qrcode_key", "url"], str]: ...
    def poll_login_qrcode(
        self, qrcode_key: str
    ) -> dict[
        Literal["message", "code", "timestamp", "refresh_token", "url"], int | str
    ]: ...
    def __poll_login_qrcode_req(self, qrcode_key: str) -> dict[str, int | str]: ...
    @staticmethod
    def cookiejar_from_crossdomain_url(url: str) -> MozillaCookieJar: ...